/**
 * Generates `supabase/seed.sql` from the existing hand-authored dataset in
 * `src/data/dataset.ts`, so the seeded Supabase database contains exactly the
 * same employers, job orders, contracts, fees, requirements, documents, notes,
 * verification events, system presets and activity feed the prototype shipped
 * with.
 *
 * The dataset is TypeScript that imports via the `@` alias, so it is bundled
 * with esbuild (already a Vite dependency) before being evaluated in Node.
 *
 *   node scripts/generate-seed.mjs
 *
 * Primary keys are deterministic UUIDv5 values derived from the original
 * domain ids (`emp-101`, `emp-101-job-1`, …) which makes the generated seed
 * idempotent — re-running it upserts instead of duplicating.
 */
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const srcDir = join(root, 'src');

/* ------------------------------------------------------------------ */
/* Deterministic UUIDv5                                               */
/* ------------------------------------------------------------------ */

const NAMESPACE = 'ef2c7c1a-1f5e-4b3a-9d2e-7a6b5c4d3e2f';

function uuidV5(name) {
  const ns = Buffer.from(NAMESPACE.replace(/-/g, ''), 'hex');
  const hash = createHash('sha1').update(ns).update(Buffer.from(name, 'utf8')).digest();
  const bytes = Buffer.from(hash.subarray(0, 16));
  bytes[6] = (bytes[6] & 0x0f) | 0x50; // version 5
  bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant
  const hex = bytes.toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

/* ------------------------------------------------------------------ */
/* SQL literal helpers                                                */
/* ------------------------------------------------------------------ */

const s = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v === null || v === undefined ? 'NULL' : String(Number(v)));
const b = (v) => (v ? 'true' : 'false');
const ts = (v) => (v === null || v === undefined ? 'NULL' : s(v));
const jsonb = (v) => `${s(JSON.stringify(v ?? {}))}::jsonb`;
const textArray = (arr) =>
  !arr || !arr.length ? `'{}'` : `array[${arr.map((x) => s(x)).join(', ')}]`;

/* ------------------------------------------------------------------ */
/* Bundle + load the dataset                                          */
/* ------------------------------------------------------------------ */

const tmp = mkdtempSync(join(tmpdir(), 'efms-seed-'));
const outfile = join(tmp, 'dataset.mjs');

try {
  await build({
    entryPoints: [join(srcDir, 'data', 'dataset.ts')],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node18',
    alias: { '@': srcDir },
    logLevel: 'warning',
  });

  const { DATASET } = await import(pathToFileURL(outfile).href);

  const lines = [];
  const push = (...xs) => lines.push(...xs);

  push(
    '-- ============================================================================',
    '-- EFMS seed data — generated by scripts/generate-seed.mjs. Do not edit by hand.',
    '-- Shared agency data only. Per-user rows (settings, notifications, shortlist)',
    '-- are created automatically when a user signs up.',
    '-- Idempotent: deterministic UUIDs + ON CONFLICT DO UPDATE.',
    '-- ============================================================================',
    '',
    'begin;',
    '',
  );

  /* ---- employers -------------------------------------------------- */
  const empId = new Map(DATASET.employers.map((e) => [e.id, uuidV5(e.id)]));
  push('-- Employers');
  for (const e of DATASET.employers) {
    push(
      `insert into public.employers (id, company_name, legal_name, logo_initials, logo_hue, registration_number, country, country_code, city, address, industry, company_size, website, contact_person, contact_role, email, phone, years_operating, status, verification, verification_stage, verification_updated_at, description, updated_by, created_at, updated_at) values (` +
        [
          s(empId.get(e.id)), s(e.companyName), s(e.legalName), s(e.logoInitials), n(e.logoHue),
          s(e.registrationNumber), s(e.country), s(e.countryCode), s(e.city), s(e.address),
          s(e.industry), s(e.companySize), s(e.website), s(e.contactPerson), s(e.contactRole),
          s(e.email), s(e.phone), n(e.yearsOperating), s(e.status), s(e.verification),
          n(e.verificationStage), ts(e.verificationUpdatedAt), s(e.description), s(e.updatedBy),
          ts(e.createdAt), ts(e.updatedAt),
        ].join(', ') +
        `) on conflict (id) do update set company_name = excluded.company_name, status = excluded.status, verification = excluded.verification, updated_at = excluded.updated_at;`,
    );
  }
  push('');

  /* ---- job orders ------------------------------------------------- */
  const jobId = new Map(DATASET.jobs.map((j) => [j.id, uuidV5(j.id)]));
  push('-- Job orders');
  for (const j of DATASET.jobs) {
    push(
      `insert into public.job_orders (id, employer_id, reference, position, job_category, workers_needed, workers_deployed, salary_min_local, salary_max_local, currency, salary_min_php, salary_max_php, working_hours, overtime, contract_duration_months, employment_type, benefits, requirements, status, posted_at) values (` +
        [
          s(jobId.get(j.id)), s(empId.get(j.employerId)), s(j.reference), s(j.position),
          s(j.jobCategory), n(j.workersNeeded), n(j.workersDeployed), n(j.salaryMinLocal),
          n(j.salaryMaxLocal), s(j.currency), n(j.salaryMinPhp), n(j.salaryMaxPhp),
          s(j.workingHours), s(j.overtime), n(j.contractDurationMonths), s(j.employmentType),
          jsonb(j.benefits), textArray(j.requirements), s(j.status), ts(j.postedAt),
        ].join(', ') +
        `) on conflict (id) do update set position = excluded.position, status = excluded.status;`,
    );
  }
  push('');

  /* ---- contracts -------------------------------------------------- */
  push('-- Contracts');
  for (const c of DATASET.contracts) {
    push(
      `insert into public.contracts (id, employer_id, contract_number, job_order_id, start_date, end_date, duration_months, salary_min_local, salary_max_local, currency, working_conditions, renewal_status, status, signed_at, notes) values (` +
        [
          s(uuidV5(c.id)), s(empId.get(c.employerId)), s(c.contractNumber),
          c.jobOrderId ? s(jobId.get(c.jobOrderId)) : 'NULL', ts(c.startDate), ts(c.endDate),
          n(c.durationMonths), n(c.salaryMinLocal), n(c.salaryMaxLocal), s(c.currency),
          s(c.workingConditions), s(c.renewalStatus), s(c.status), ts(c.signedAt), s(c.notes),
        ].join(', ') +
        `) on conflict (id) do update set status = excluded.status, end_date = excluded.end_date;`,
    );
  }
  push('');

  /* ---- fees ------------------------------------------------------- */
  push('-- Fees');
  for (const f of DATASET.fees) {
    push(
      `insert into public.fees (id, employer_id, type, amount, currency, borne_by, payment_status, due_date, notes) values (` +
        [
          s(uuidV5(f.id)), s(empId.get(f.employerId)), s(f.type), n(f.amount), s(f.currency),
          s(f.borneBy), s(f.paymentStatus), ts(f.dueDate), s(f.notes),
        ].join(', ') +
        `) on conflict (id) do update set amount = excluded.amount, payment_status = excluded.payment_status;`,
    );
  }
  push('');

  /* ---- requirements ----------------------------------------------- */
  push('-- Requirements');
  for (const r of DATASET.requirements) {
    push(
      `insert into public.requirements (id, employer_id, key, label, description, completed, status, mandatory, updated_at) values (` +
        [
          s(uuidV5(r.id)), s(empId.get(r.employerId)), s(r.key), s(r.label), s(r.description),
          b(r.completed), s(r.status), b(r.mandatory), ts(r.updatedAt),
        ].join(', ') +
        `) on conflict (id) do update set completed = excluded.completed, status = excluded.status;`,
    );
  }
  push('');

  /* ---- documents -------------------------------------------------- */
  push('-- Documents (metadata only; no storage object for seeded rows)');
  for (const d of DATASET.documents) {
    push(
      `insert into public.documents (id, employer_id, name, type, file_name, file_size_kb, uploaded_at, uploaded_by, expires_at, status, notes) values (` +
        [
          s(uuidV5(d.id)), s(empId.get(d.employerId)), s(d.name), s(d.type), s(d.fileName),
          n(d.fileSizeKb), ts(d.uploadedAt), s(d.uploadedBy), ts(d.expiresAt), s(d.status), s(d.notes),
        ].join(', ') +
        `) on conflict (id) do update set status = excluded.status, notes = excluded.notes;`,
    );
  }
  push('');

  /* ---- notes ------------------------------------------------------ */
  push('-- Notes');
  for (const note of DATASET.notes) {
    push(
      `insert into public.notes (id, employer_id, author, body, pinned, created_at) values (` +
        [
          s(uuidV5(note.id)), s(empId.get(note.employerId)), s(note.author), s(note.body),
          b(note.pinned), ts(note.createdAt),
        ].join(', ') +
        `) on conflict (id) do update set body = excluded.body, pinned = excluded.pinned;`,
    );
  }
  push('');

  /* ---- verification events ---------------------------------------- */
  push('-- Verification events');
  for (const v of DATASET.verificationEvents) {
    push(
      `insert into public.verification_events (id, employer_id, stage, actor, outcome, comment, occurred_at) values (` +
        [
          s(uuidV5(v.id)), s(empId.get(v.employerId)), s(v.stage), s(v.actor), s(v.outcome),
          s(v.comment), ts(v.timestamp),
        ].join(', ') +
        `) on conflict (id) do update set outcome = excluded.outcome, comment = excluded.comment;`,
    );
  }
  push('');

  /* ---- system filter presets -------------------------------------- */
  push('-- System filter presets (shared, read-only)');
  for (const p of DATASET.presets) {
    push(
      `insert into public.filter_presets (id, user_id, name, description, filters, system, use_count, last_used_at, created_at) values (` +
        [
          s(uuidV5(p.id)), 'NULL', s(p.name), s(p.description), jsonb(p.filters), b(p.system),
          n(p.useCount), ts(p.lastUsedAt), ts(p.createdAt),
        ].join(', ') +
        `) on conflict (id) do update set name = excluded.name, description = excluded.description, filters = excluded.filters;`,
    );
  }
  push('');

  /* ---- activity log ----------------------------------------------- */
  push('-- Activity log (agency-wide; seeded rows are unattributed)');
  for (const a of DATASET.activity) {
    push(
      `insert into public.activity_log (id, user_id, user_name, user_initials, action, action_type, employer_id, employer_name, detail, created_at) values (` +
        [
          s(uuidV5(a.id)), 'NULL', s(a.user), s(a.userInitials), s(a.action), s(a.actionType),
          a.employerId ? s(empId.get(a.employerId)) : 'NULL', s(a.employerName), a.detail ? s(a.detail) : 'NULL',
          ts(a.timestamp),
        ].join(', ') +
        `) on conflict (id) do nothing;`,
    );
  }
  push('');

  push('commit;', '');

  writeFileSync(join(root, 'supabase', 'seed.sql'), lines.join('\n'), 'utf8');

  const counts = {
    employers: DATASET.employers.length,
    job_orders: DATASET.jobs.length,
    contracts: DATASET.contracts.length,
    fees: DATASET.fees.length,
    requirements: DATASET.requirements.length,
    documents: DATASET.documents.length,
    notes: DATASET.notes.length,
    verification_events: DATASET.verificationEvents.length,
    filter_presets: DATASET.presets.length,
    activity_log: DATASET.activity.length,
  };
  console.log('Wrote supabase/seed.sql');
  console.table(counts);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
